version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version && docker --version && docker ps
      - $(aws ecr get-login --region eu-west-1 --no-include-email)
      - REPOSITORY_URI=486652066693.dkr.ecr.eu-west-1.amazonaws.com/nginx
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest nginx/.
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nginx","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
